[package]
name = "softbuffer"
version = "0.0.1"
edition = "2021"
authors = ["David Johnson <john01dav@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Softbuffer integrates with the raw-window-handle crate to allow writing to a window in a cross-platform way while using the very high quality dedicated window management libraries that are available in the Rust ecosystem."

[dependencies]
thiserror = "1.0.30"
raw-window-handle = "0.4.2"

[target.'cfg(target_os = "linux")'.dependencies]
x11-dl = "2.19.1"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
winit = "0.26.1"